/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package mailserverproject;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.File;
import javax.swing.UIManager;

/**
 *
 * @author Dell
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form UDPClient
     */
    public SignUp() {
       
      initComponents();
        // Thiết lập placeholder cho username_form
    setupPlaceholder(username_form, "Username");
    
    // Thiết lập placeholder cho password_form
    setupPlaceholder(password_form, "Password");
    
    
    this.addWindowFocusListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            // Focus vào nút "Sign In" hoặc phần khác
            signIn_form_button.requestFocusInWindow();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password_form = new javax.swing.JTextField();
        username_form = new javax.swing.JTextField();
        signIn_form_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        signUp_form_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 85, 87));
        jLabel2.setText("Sign Up");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, 62));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 52, 51));
        jLabel3.setText("Enter your account");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 120, 20));

        password_form.setBackground(new java.awt.Color(204, 204, 204));
        password_form.setForeground(new java.awt.Color(102, 102, 102));
        password_form.setText("Password");
        password_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_formActionPerformed(evt);
            }
        });
        jPanel2.add(password_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 340, 50));

        username_form.setBackground(new java.awt.Color(204, 204, 204));
        username_form.setForeground(new java.awt.Color(102, 102, 102));
        username_form.setText("Username");
        username_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_formActionPerformed(evt);
            }
        });
        jPanel2.add(username_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 340, 50));

        signIn_form_button.setBackground(new java.awt.Color(101, 131, 96));
        signIn_form_button.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        signIn_form_button.setForeground(new java.awt.Color(255, 255, 255));
        signIn_form_button.setText("Sign Up");
        signIn_form_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signIn_form_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(signIn_form_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 200, 40));

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));

        jLabel4.setForeground(new java.awt.Color(52, 52, 51));
        jLabel4.setText("If you have account.");
        jPanel3.add(jLabel4);

        signUp_form_button.setBackground(new java.awt.Color(117, 155, 117));
        signUp_form_button.setText(" Log In");
        signUp_form_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUp_form_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(signUp_form_button);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 260, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 390, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mailserverproject/images/hihihaha.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 860, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupPlaceholder(javax.swing.JTextField textField, String placeholder) {
    textField.setText(placeholder);
    textField.setForeground(Color.GRAY);
    
    textField.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            if (textField.getText().equals(placeholder)) {
                textField.setText("");
                textField.setForeground(Color.BLACK); // Đổi lại màu chữ khi người dùng nhập
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            if (textField.getText().isEmpty()) {
                textField.setText(placeholder);
                textField.setForeground(Color.GRAY); // Đặt lại màu chữ và placeholder nếu trống
            }
        }
    });
}

    private void password_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_formActionPerformed
      
    }//GEN-LAST:event_password_formActionPerformed

    private void signIn_form_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signIn_form_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signIn_form_buttonActionPerformed

    private void signUp_form_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUp_form_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUp_form_buttonActionPerformed

    private void username_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_formActionPerformed
         
    }//GEN-LAST:event_username_formActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
// System.setProperty("sun.java2d.uiScale", "1.0");
 try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (Exception e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField password_form;
    private javax.swing.JButton signIn_form_button;
    private javax.swing.JButton signUp_form_button;
    private javax.swing.JTextField username_form;
    // End of variables declaration//GEN-END:variables

}
